test_cases:
  case_001:
    body: {}
    headers:
      Content-Type: application/json
    method: GET
    name: 获取用户信息
    params:
      user_id: '12345'
  case_002:
    body:
      email: test@example.com
      username: test_user
    headers:
      Content-Type: application/json
    method: POST
    name: 创建新用户
    params: {}
  case_1:
    body:
      body: Short Content
      title: Short Title
      userId: 1
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_1
    params: {}
  case_2:
    body:
      body: Normal Content
      title: Normal Title
      userId: 50
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_2
    params: {}
  case_3:
    body:
      body: Edge Case Content
      title: Edge Case Title
      userId: 1
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_3
    params: {}
  case_4:
    body:
      body: Empty Title
      title: ''
      userId: 10
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_4
    params: {}
  case_5:
    body:
      body: Special Characters Content
      title: Special Characters !@#$%
      userId: 20
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_5
    params: {}
  case_6:
    body:
      body: Long Content More Than 1000 Characters Long Content More Than 1000 Characters
        Long Content More Than 1000 Characters Long Content More Than 1000 Characters
        Long Content More Than 1000 Characters Long Content More Than 1000 Characters
        Long Content More Than 1000 Characters Long Content More Than 1000 Characters
        Long Content More Than 1000 Characters Long Content More Than 1000 Characters
        Long Content More Than 1000 Characters Long Content More Than 1000 Characters
      title: Long Title More Than 100 Characters Long Title More Than 100 Characters
      userId: 30
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_6
    params: {}
  case_7:
    body:
      body: Invalid User ID
      title: Normal Title
      userId: 101
    headers:
      Accept: application/json
      Content-Type: application/json
    method: POST
    name: case_7
    params: {}
