test_cases:
  case_773:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_936
    params:
      test_param: test_param_value
test_cases:
  case_275:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_164
    params:
      test_param: test_param_value
test_cases:
  case_949:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_245
    params:
      test_param: test_param_value
test_cases:
  case_553:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_941
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_941
    params:
      test_param: test_param_value
  case_886:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_207
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_207
    params:
      test_param: test_param_value
  case_229:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_946
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_946
    params:
      test_param: test_param_value
  case_948:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_1000
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_759
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_437
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_495
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_659
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_382
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_74
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_835
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_402
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_691
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_960
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_136
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_981
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_274
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      test_body: test_body_value
    headers:
      test_header: test_header_value
    method: test_method
    name: case_362
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      body: 测试内容
      title: 测试标题
      userId: 1
    headers:
      test_header: test_header_value
    method: test_method
    name: case_506
    params:
      test_param: test_param_value
test_cases:
  c:
    api_key: test_api_key
    api_secret: test_api_secret
    api_url: test_api_url
    body:
      body: 测试内容
      title: 测试标题
      userId: 1
    headers:
      test_header: test_header_value
    method: test_method
    name: case_477
    params:
      test_param: test_param_value
